jobs:
  build:
    name: Documentation Build on Java ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build Project
      run: 'git config --global user.email "${GITHUB_ACTOR}"

        git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"

        ./doc/ci-docs.sh

        '
    strategy:
      matrix:
        java:
        - 11
name: Documentation Build
on:
  repository_dispatch:
    types: trigger-ga___doc-build.yml
