env:
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e
jobs:
  windows-build:
    name: Windows
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Get Windows Version > Used to retrieve specific Docker Image
      run: 'ver

        '
      shell: cmd
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - continue-on-error: true
      name: Install DMP
      run: mvn ${MAVEN_ARGS} clean install -DskipTests
    - continue-on-error: true
      name: Run Integration tests
      run: 'cd it/windows-build

        mvn clean install -Pwindows

        '
name: E2E Windows
on:
  repository_dispatch:
    types: trigger-ga___e2e-windows.yml
