concurrency:
  cancel-in-progress: true
  group: ci-e2e-docker-maven-plugin-${{ github.ref }}
env:
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e
jobs:
  buildWithoutTests:
    name: BuildWithoutTests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Cache .m2 registry
      uses: actions/cache@v4
      with:
        key: cache-e2e-${{ github.sha }}-${{ github.run_id }}
        path: ~/.m2/repository
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - continue-on-error: true
      name: Install DMP
      run: mvn ${MAVEN_ARGS} clean install -DskipTests -Djacoco.skip=true
  linux-build:
    name: Linux
    needs: buildWithoutTests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - continue-on-error: true
      name: Cache .m2 registry
      uses: actions/cache@v4
      with:
        key: cache-e2e-${{ github.sha }}-${{ github.run_id }}
        path: ~/.m2/repository
    - continue-on-error: true
      name: Set up Docker
      uses: crazy-max/ghaction-setup-docker@v2
      with:
        version: ${{ matrix.docker }}
    - continue-on-error: true
      name: Run Integration tests
      run: '# Workaround for https://github.com/docker/for-linux/issues/748

        DOCKER_INSTALL_PATH=`which docker`

        sudo cp $DOCKER_INSTALL_PATH-init /sbin/docker-init

        cd it/

        mvn clean install

        '
    strategy:
      fail-fast: false
      matrix:
        docker:
        - v25.0.2
        - v24.0.9
        - v23.0.6
        - v20.10.24
  macos-build:
    name: MacOS
    needs: buildWithoutTests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - continue-on-error: true
      name: Cache .m2 registry
      uses: actions/cache@v4
      with:
        key: cache-e2e-${{ github.sha }}-${{ github.run_id }}
        path: ~/.m2/repository
    - continue-on-error: true
      name: Set up Docker
      uses: crazy-max/ghaction-setup-docker@v2
      with:
        version: ${{ matrix.docker }}
    - continue-on-error: true
      name: Set up Docker Buildx
      run: 'brew install docker-buildx

        mkdir -p ~/.docker/cli-plugins

        ln -sfn /usr/local/opt/docker-buildx/bin/docker-buildx ~/.docker/cli-plugins/docker-buildx

        '
    - continue-on-error: true
      name: Run Integration tests
      run: 'export DOCKER_HOST=unix:///Users/runner/.colima/default/docker.sock

        cd it/

        mvn clean install

        '
    strategy:
      fail-fast: false
      matrix:
        docker:
        - v25.0.2
        - v24.0.9
        - v23.0.6
        - v20.10.24
name: E2E Tests
on:
  repository_dispatch:
    types: trigger-ga___e2e-tests.yml
