jobs:
  build:
    name: Java ${{ matrix.java }} Maven Wrapper
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build Project
      run: ./mvnw -B -C -V -ntp clean install
    strategy:
      matrix:
        java:
        - 11
name: Mac OS Build
on:
  repository_dispatch:
    types: trigger-ga___macos-mavenwrapper-build.yml
