env:
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e ${{ github.event.inputs.additional_args
    }}
  OSSRHPASSWORD: ${{ secrets.OSSRHPASSWORD }}
  OSSRHUSERNAME: ${{ secrets.OSSRHUSERNAME }}
  RELEASE_MAVEN_ARGS: -Prelease -Denforcer.skip=true
  SIGNINGPASSWORD: ${{ secrets.SIGNINGPASSWORD }}
jobs:
  release-snapshots:
    if: contains('["rhuss","rohanKanojia"]', github.actor)
    name: Release SNAPSHOT
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        gpg-passphrase: SIGNINGPASSWORD
        gpg-private-key: ${{ secrets.SIGNINGKEY }}
        java-version: 11
        server-id: sonatype-nexus-snapshots
        server-password: OSSRHPASSWORD
        server-username: OSSRHUSERNAME
    - continue-on-error: true
      name: Build and Release Project
      run: ./mvnw ${MAVEN_ARGS} ${RELEASE_MAVEN_ARGS} clean deploy
name: Release to SNAPSHOTS Maven Central
on:
  repository_dispatch:
    types: trigger-ga___release-snapshots.yml
