concurrency:
  cancel-in-progress: true
  group: ci-sonar-docker-maven-plugin-${{ github.ref }}
env:
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e
jobs:
  sonar:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.number }}
      SONAR_LOGIN_TOKEN: ${{ secrets.SONAR_LOGIN_TOKEN }}
    name: Sonar PR Scanner
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Maven Sonar
      run: "./mvnw ${MAVEN_ARGS} -Pjacoco,sonar clean install \\\n   -Dsonar.projectKey=fabric8io_docker-maven-plugin\
        \ \\\n   -Dsonar.organization=fabric8io \\\n   -Dsonar.login=${SONAR_LOGIN_TOKEN}\
        \ \\\n   -Dsonar.host.url=https://sonarcloud.io \\\n   -Dsonar.pullrequest.base=master\
        \ \\\n   -Dsonar.pullrequest.branch=${GITHUB_BASE_REF} \\\n   -Dsonar.pullrequest.key=${PR_NUMBER}\
        \ \\\n   -Dsonar.pullrequest.provider=GitHub \\\n   -Dsonar.pullrequest.github.repository=fabric8io/docker-maven-plugin\
        \ \\\n   -Dsonar.github.oauth=${GITHUB_TOKEN}\n"
name: Sonar PR Scanner
on:
  repository_dispatch:
    types: trigger-ga___sonar-pr.yml
permissions:
  contents: read
